### ISSUE TITLE
New Console App

### ISSUE THREAD

**Issue by JReming85** [devnulli/EvlWatcher#1]
Any chance on a new console app when you finish the rewrite?

**Comment by devnulli** [comment]
Yes the rewrite will be done on May 9th including a new console app

**Comment by JReming85** [comment]
Cant wait, thank you for doing this.

So far much better then Cyberarm's software for me atleast.  My server averages around 500k attacks a month and their would constantly use around 30% of my cpu and the db would lock up since it was around 2gb in size.

So far your software is only using around 10% cpu and not that often, majority of the time its at 0%.

Cant wait to see the rewrite's performance.
