### ISSUE TITLE
Adding sql server logons

### ISSUE THREAD

**Issue by alij** [devnulli/EvlWatcher#100]
Please find event log for sql server logon attempts. It's in "Windows Logs"/Applications in EventViewer:

<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="MSSQLSERVER" /> 
  <EventID Qualifiers="49152">18456</EventID> 
  <Level>0</Level> 
  <Task>4</Task> 
  <Keywords>0x90000000000000</Keywords> 
  <TimeCreated SystemTime="2022-07-21T10:05:52.529488700Z" /> 
  <EventRecordID>6145709</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>...</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>sa</Data> 
  <Data>Reason: Password did not match that for the login provided.</Data> 
  <Data>[CLIENT: 58.65.179.248]</Data> 
  <Binary>...</Binary> 
  </EventData>
  </Event>

**Comment by manhthang2504** [comment]
I have same need.

Basically I opened the config.xml and add following:

```
<Task Name="BlockMSSQLBruteforce" Active="true">
			<!-- the description ..-->
			<Description>
				This rule checks for failed SQL Server logins.
			</Description>
			<!-- this is the time a temporary ban is issued for, in seconds-->
			<LockTime>
				3600
			</LockTime>
			
			<!-- this is used for rules that only need new events for evaluating.
			      - If you dont know what this does, leave it set to false
				  
				  - If you set this to true, it means that the task will only receive events it has not already received
				  
				  - If you set this to false, it means that the task will receive all events of its timeframe, everytime it is polled 
				     (e.g. task gets events provided until they fall out of the timeframe)-->
			<OnlyNew>
				False
			</OnlyNew>
			<!-- this is the timeframe (in seconds) to be inspected-->
			<EventAge>
				120
			</EventAge>
			<!-- this is the amount of times an entry must occure within the time frame to be considered a brute force attempt-->
			<TriggerCount>
				5
			</TriggerCount>
			<!-- after this amount of times temporarily banned, the ban will become permanent -->
			<PermaBanCount>
				3
			</PermaBanCount>
			<!-- This is the place where the rule looks for entries-->
			<EventPath>
				Application
			</EventPath>
			<!-- This was introduced because sole regex matching is too CPU intensive. it incredibly speeds up the filtering when you enter some (or at least one) words that MUST be contained in the LogEntry to undergo the regex inspection-->
			<RegexBoosters>
				<Booster>Failed password</Booster>
			</RegexBoosters>
			<!-- This is the regex that tries to extract an IP from the entries that contain the booster words for more infos see regex101.com-->
			<Regex>
				(\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b)
			</Regex>
		</Task>
```

This rule does not show up in the Evl Watch Console's Rule Tester tab, and of course it does not work.

Please check whether the config.xml is really loaded, or just for demo purpose?

**Comment by manhthang2504** [comment]
> I have same need.
> 
> Basically I opened the config.xml and add following:
> 
> ```
> <Task Name="BlockMSSQLBruteforce" Active="true">
> 			
> 			<Description>
> 				This rule checks for failed SQL Server logins.
> 			</Description>
> 			
> 			<LockTime>
> 				3600
> 			</LockTime>
> 			
> 			
> 			<OnlyNew>
> 				False
> 			</OnlyNew>
> 			
> 			<EventAge>
> 				120
> 			</EventAge>
> 			
> 			<TriggerCount>
> 				5
> 			</TriggerCount>
> 			
> 			<PermaBanCount>
> 				3
> 			</PermaBanCount>
> 			
> 			<EventPath>
> 				Application
> 			</EventPath>
> 			
> 			<RegexBoosters>
> 				<Booster>Failed password</Booster>
> 			</RegexBoosters>
> 			
> 			<Regex>
> 				(\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b)
> 			</Regex>
> 		</Task>
> ```
> 
> This rule does not show up in the Evl Watch Console's Rule Tester tab, and of course it does not work.
> 
> Please check whether the config.xml is really loaded, or just for demo purpose?

I just found out that I need to restart the evlwatch services (run: services.msc) or restart the computer. After restart the service, the rules in config is loaded into Rule Tester tab, but still not working.

**Comment by devnulli** [comment]
i will add that to default rules
