### ISSUE TITLE
Support Watching SMB Server

### ISSUE THREAD

**Issue by haoyangw** [devnulli/EvlWatcher#102]
Custom Task to catch authentication failure events from SMBServer to prevent brute force attacks(works when tested with EvlWatcher Console using a purposeful authentication failure event XML, IP is extracted successfully)

		
		<Task Name="BlockSMBBruters" Active="true">
			
			<Description>
				This rule checks for failed SMB logins.
			</Description>
			
			<LockTime>
				3600
			</LockTime>
			
			
			<OnlyNew>
				False
			</OnlyNew>
			
			<EventAge>
				120
			</EventAge>
			
			<TriggerCount>
				5
			</TriggerCount>
			
			<PermaBanCount>
				3
			</PermaBanCount>
			
			<EventPath>
				Microsoft-Windows-SMBServer/Security
			</EventPath>
			
			<RegexBoosters>
				<Booster>SMB Session Authentication Failure</Booster>
			</RegexBoosters>
			
			<Regex>
				(\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b)
			</Regex>
		</Task>

**Comment by devnulli** [comment]
thanks, will add this
