### ISSUE TITLE
sugestion

### ISSUE THREAD

**Issue by fbocosta** [devnulli/EvlWatcher#104]
I think it would be very valid to have the option of blocking by regions as well as having the blocking by ip range.

**Comment by devnulli** [comment]
hi,
thanks for your suggestion, 
yes you're right that would be useful, but that would make EvlWatcher too intelligent. Its designed as stupid logfile analyzer, not knowing its environment and also, not even having internet access.  it should work kindof like fail2ban

so, im afraid i cant do that at the moment
