### ISSUE TITLE
just broken.

### ISSUE THREAD

**Issue by progger8888** [devnulli/EvlWatcher#114]
1. install EvlWatcher
2. wait a moment until the first ip´s hits the blocklist
3. change checkinterval to 120 sec.

Thats all, nothing will work anymore and a reinstall wont fix the issue.

**Comment by RickkeeC** [comment]
Maybe stop service, delete your config.xml and restore from original, start service?  I found that one typo can cause it to fail.

**Comment by devnulli** [comment]
ima try to reproduce that, but the given scenario works fine with me. which OS are you on?
