### ISSUE TITLE
Make config.xml options configurable via UI

### ISSUE THREAD

**Issue by Pepo48** [devnulli/EvlWatcher#115]
[UX enhancement]

**Comment by RickkeeC** [comment]
+1 A gui for this would be swell.  Also would like ability to start / stop service from UI

**Comment by devnulli** [comment]
its just too much work to add a ui for task configuration. for the other things theres already a very pathetic ui in your service executable directory, you can restart the service there and do some other things.

adding such a ui would bring up a lot of issues that dont focus on the core job of evlwatcher, and i only have limited time to maintain that core part
