### ISSUE TITLE
Whitelist not working

### ISSUE THREAD

**Issue by RickkeeC** [devnulli/EvlWatcher#117]
have added 192.168.1.*  and 192.168.1.102, however  192.168.1.102 stoll gets temporary band, then then permanently banned.  What could be wrong?
Also, where does EVL store permeant bans?  I don't see them in Windows firewall rules.  (Its only for temporary)

**Comment by RickkeeC** [comment]
bump...help...anyone home...I am ready and willing to buy more coffee.

**Comment by devnulli** [comment]
ye ye im here ill fix it :D

**Comment by RickkeeC** [comment]
Sending another cup of coffee as a bribe :) Still dealing with this issue of trusted AND banned.  sigh Customers get banned, when they are supposed to be trusted.
![Banned AND Trusted 2023-08-29 17_05_44](https://github.com/devnulli/EvlWatcher/assets/40076667/27c22556-e893-484f-af02-03b79222a07f)

**Comment by devnulli** [comment]
okay ill look into it :D

**Comment by devnulli** [comment]
@RickkeeC  are you using the newest version?

**Comment by RickkeeC** [comment]
Version 2.1.5 .  Had to respond to another request today, where the external IP address was already in the xwhitex _trusted_-list
entered as 123.456.789.123 and as 123.456.789.0/24 .  But still, it got banned after the set 5 attempts.  Stop everything and go fix it for the client.  Sending a third cup of coffee - thanks for an almost perfect program.

**Comment by JReming85** [comment]
In case you need an immediate solution, thoughts on using an RDP Gateway, so lower the amount of IP's on the whitelist?

Either server built-in role or the open-source version https://github.com/bolkedebruin/rdpgw
or using something Rustdesk https://rustdesk.com/ for remote access

**Comment by RickkeeC** [comment]
Gateway + VPN would be the ultimate solution, as would smart firewall like Sonicwall or Zyxel but client dont wanna pay.  Plus, it is awkward for client to switch between servers that use rdweb, and those that dont.  Have to save separate files because MSTSC always remembers last setting and working with clients is PIA anyhow.

**Comment by RickkeeC** [comment]
consider $12 per year, per site for site license and that will give you the $$$ to develop a pro version.  I will take 30 of them $$$

**Comment by JReming85** [comment]
> Gateway + VPN would be the ultimate solution, as would smart firewall like Sonicwall or Zyxel but client dont wanna pay. Plus, it is awkward for client to switch between servers that use rdweb, and those that dont. Have to save separate files because MSTSC always remembers last setting and working with clients is PIA anyhow.

Rustdesk is a free selfhosted TeamViewer clone.

You can set keypairs for encryption to/from relay and have it auto reject connections without it.

Is a desktop client where the client can fav their servers so they are always listed.  They even have a paid version that offers an address book

**Comment by devnulli** [comment]
so, i have just ordered a new code signing certificate to release a fixed version of EvlWatcher.

**Comment by devnulli** [comment]
i just analyzed this, this is a display issue. The permanent bans from the tasks are displayed without running through the whitelist. However, they are not banned.

so: they are dispöayed as banned, while they are not. I will fix the display issue tho

**Comment by RickkeeC** [comment]
Hello, that is good to hear, sounds like maybe a simple fix, but I seem to recall having had it fail with trusted external IP blocks where they show up on both sides and are indeed blocked.
FYI, In my case, restarting the service does not change anything with the display.
Thank you so much for looking into this, a fresh coffee awaits you. 😊

**Comment by RickkeeC** [comment]
Hello.  Yes and thank you.
Rick Cassel

**Comment by devnulli** [comment]
ok, so could you please put this to the test then
https://github.com/devnulli/EvlWatcher/blob/v2.1.6/Versions/v2/EvlWatcher-v2.1.6pre-setup.exe

thank you

**Comment by RickkeeC** [comment]
Hello,

FYI, I've only managed to install it on 4 devices, but so far after a month and two months
it appears to be working correctly regarding the ghost trusted and blocked.

Rick

**Comment by Drag-NDrop** [comment]
Hello Sir,

Is it possible to read the code of 2.1.6 somewhere? I see it's in the works, and I'm quite interested in setting up a solution for myself. And i'd rather use this and contribute to it, than throw money at RDPGuard.

**Comment by devnulli** [comment]
ok. i release now
