### ISSUE TITLE
RDWEB logging - Event Log Microsoft-Windows-IIS-Logging/Logs was not found

### ISSUE THREAD

**Issue by domstrumidlo** [devnulli/EvlWatcher#122]
Hello,
I've created custom task list that follows:
```
  <Tasks>
    <Task Name="BlockRDWEBBruteAttacks" Active="true">
      <Description>
				This rule checks for failed RDweb Gateway IIS login attempts
			</Description>
      <LockTime>
				360
			</LockTime>
      <OnlyNew>
				False
			</OnlyNew>
      <EventAge>
				360
			</EventAge>
      <TriggerCount>
				5
			</TriggerCount>
      <PermaBanCount>
				2
			</PermaBanCount>
      <EventPath>
				Microsoft-Windows-IIS-Logging/Logs
			</EventPath>
      <RegexBoosters>
        <Booster>6200</Booster>
      </RegexBoosters>
      <Regex>
				&lt;Data Name="c-ip"&gt;(\d*.\d*.\d*.\d*)&lt;\/Data&gt;.*\n.*\n.*\n.*\n.*.*\n.*&lt;Data Name="cs-method"&gt;POST&lt;\/Data&gt;.*\n.*&lt;Data Name="cs-uri-stem"&gt;\/RDWeb\/Pages\/pl-PL\/login\.aspx&lt;\/Data&gt;.*\n.*\n.*&lt;Data Name="sc-status"&gt;200&lt;\/Data&gt;.*\n.*&lt;Data Name="sc-win32-status"&gt;0&lt;\/Data&gt;.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*&lt;Data Name="sc-substatus"&gt;0&lt;\/Data&gt;
			</Regex>
    </Task>

```

I have turned on logs on IIS manager for this site 

> IIS Manager -> server -> Sites -> Default Web Site -> Logging ->
> Log event Destination -> Both log and ETW event
> 

Also turned on IIS log at Event Viewer 

> Event Viewer -> Applications and Services Logs -> Microsoft -> IIS-Logging -> Logs 
> Right click on Logs -> Enable Logs

Did few test to make sure that something is happening in those logs. 
then Restarted Service -> EvlWatcher Service, but there is info 
`SomeTime - [Info]: Event Log Microsoft-Windows-IIS-Logging/Logs was not found, tasks that require these events will not work and are disabled.`

I'm using WS2022DC

**Comment by devnulli** [comment]
Hi, you said there are actual log entries in there? if so, open them as xml and check if your eventpath matches the log name

**Comment by domstrumidlo** [comment]
Indeed there is mismatch in naming system for this log.
correct name is
Microsoft-IIS-Logging/Logs

I found out that parsed XML logs does not contain newline so I have reworked regexfor that and to be more universal (multi-language) and then tested this rule with success. 

Using GET finds out bruteforce that provide no domain name, and correct regex for that is 

><Data Name=.c-ip.>(\d*.\d*.\d*.\d*)<\/Data>.*<Data Name=.cs-method.>GET<\/Data>.*<Data Name=.cs-uri-stem.>\/RDWeb\/Pages\/pl-PL\/login\.aspx<\/Data>.*<Data Name=.sc-status.>200<\/Data>.*<Data Name=.sc-win32-status.>0<\/Data>.*<Data Name=.sc-substatus.>0<\/Data>

Using POST finds out valid login attempts that are being brute forced. This should be default setting as most brute-force attacks will have POST anyway. Correct regex for that is

> <Data Name=.c-ip.>(\d*.\d*.\d*.\d*)<\/Data>.*<Data Name=.cs-method.>POST<\/Data>.*<Data Name=.cs-uri-stem.>\/RDWeb\/Pages\/pl-PL\/login\.aspx<\/Data>.*<Data Name=.sc-status.>200<\/Data>.*<Data Name=.sc-win32-status.>0<\/Data>.*<Data Name=.sc-substatus.>0<\/Data>

full task config for those are

```
    <Task Name="BlockRDWEBBruteAttacksPOST" Active="true">
      <Description>
				This rule checks for failed RDweb Gateway IIS login attempts (DEFAULT Settings)
			</Description>
      <LockTime>
				3600
			</LockTime>
      <OnlyNew>
				False
			</OnlyNew>
      <EventAge>
				3600
			</EventAge>
      <TriggerCount>
				5
			</TriggerCount>
      <PermaBanCount>
				2
			</PermaBanCount>
      <EventPath>
				Microsoft-IIS-Logging/Logs
			</EventPath>
      <RegexBoosters>
        <Booster>6200</Booster>
      </RegexBoosters>
      <Regex>
				&lt;Data Name=.c-ip.&gt;(\d*.\d*.\d*.\d*)&lt;\/Data&gt;.*&lt;Data Name=.cs-method.&gt;POST&lt;\/Data&gt;.*&lt;Data Name=.cs-uri-stem.&gt;\/RDWeb\/Pages\/.....\/login\.aspx&lt;\/Data&gt;.*&lt;Data Name=.sc-status.&gt;200&lt;\/Data&gt;.*&lt;Data Name=.sc-win32-status.&gt;0&lt;\/Data&gt;.*&lt;Data Name=.sc-substatus.&gt;0&lt;\/Data&gt;
			</Regex>
    </Task>
```
and GET:
```
    <Task Name="BlockRDWEBBruteAttacksGET" Active="true">
      <Description>
				This rule checks for failed RDweb Gateway IIS login attempts (without providing domain name)
			</Description>
      <LockTime>
				3600
			</LockTime>
      <OnlyNew>
				False
			</OnlyNew>
      <EventAge>
				3600
			</EventAge>
      <TriggerCount>
				5
			</TriggerCount>
      <PermaBanCount>
				2
			</PermaBanCount>
      <EventPath>
				Microsoft-IIS-Logging/Logs
			</EventPath>
      <RegexBoosters>
        <Booster>6200</Booster>
      </RegexBoosters>
      <Regex>
				&lt;Data Name=.c-ip.&gt;(\d*.\d*.\d*.\d*)&lt;\/Data&gt;.*&lt;Data Name=.cs-method.&gt;GET&lt;\/Data&gt;.*&lt;Data Name=.cs-uri-stem.&gt;\/RDWeb\/Pages\/.....\/login\.aspx&lt;\/Data&gt;.*&lt;Data Name=.sc-status.&gt;200&lt;\/Data&gt;.*&lt;Data Name=.sc-win32-status.&gt;0&lt;\/Data&gt;.*&lt;Data Name=.sc-substatus.&gt;0&lt;\/Data&gt;
			</Regex>
    </Task>
```

Above Regex can be used as feature.

**Comment by devnulli** [comment]
nice, thanks
