### ISSUE TITLE
Potential critical bug in source code. [Error][Collection was modified; enumeration operation may not execute]

### ISSUE THREAD

**Issue by ZenOption** [devnulli/EvlWatcher#125]
[Error][Collection was modified; enumeration operation may not execute]

Me, as recent user of this wonderful soft, reporting. 
There is a nasty bug somewhere, that stops parsing new journal entries. 
In debug logs, it had many 131 rules entries, and in the end mentioned that error.

Due to it, my server was open to 2 full days of relentless attacks (during weekends).
When today i noticed it, wasn't able to determine first, what was wrong, or what did broke suddenly (is it OS? is it soft? is it firewall?) , but new ip-s weren't pushed to the block list, completely broken, because main routine of parsing wasn't working at all.
In the end, decided trying to restart service, which did reanimate parsing logs.
I'm not sure if it's rare or not, but i got this only after one week of using software (which is very bad uptime ratio until broken)
Worst part is, if it wasn't for me manually checking logs, and comparing to what should be blocked, the program would be stuck as is, unable to unstuck itself, and time goes on, as if nothing is unusual. One may wonder, when would be the next time it stumbles upon same bug, and will stop doing it's only task its designed to. 

I advice developer to re-check codebase, as to where a potential bug may appear related to this problem. For example, possible reason is discussed here
(https://stackoverflow.com/questions/604831/collection-was-modified-enumeration-operation-may-not-execute)

**Comment by did-vmonroig** [comment]
This is already discussed in #88. Still happens in my servers but less frequently with latest releases.

**Comment by ZenOption** [comment]
Oh, thanks for mentioning #88.
Well, seems like it was closed prematurely, as bug still persists.
In the meantime, i would be creating additional task that re-starts service once in a while as a preemptive measure.

**Comment by devnulli** [comment]
was the message directly before that "Event Log {requiredEventType} was not found, tasks that require these events will not work and are disabled." ?

**Comment by ZenOption** [comment]
Hi, the logs were abolutely a mess, and I didn't have a chance to find out what exactly started it, or the message before it occured.
That being said, it's 'yes' to both questions. 
The Concolse was left open inside rdp session, and it repeated many failed messages (pertaining to 131 rule, in my case) at every 'check interval'. With the as an actual [Error][...enumeration operation may not execute] in the end.

**Comment by devnulli** [comment]
hi thanks for the logs, ill look into it


( btw: if you mean that 
`26.01.2024 15:10:46 - [Debug]: Booster: 131
26.01.2024 15:10:46 - [Debug]: Booster not in XML, aborting.`

thats not an error message )

**Comment by devnulli** [comment]
#126 to locate it better

**Comment by devnulli** [comment]
added code to location this bug. lets hope we get the stacktrace next time this happens.

**Comment by did-vmonroig** [comment]
This is still an issue, now with more information in event log (spanish OS):

```
Colección modificada; puede que no se ejecute la operación de enumeración.
   en System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   en System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   en EvlWatcher.Tasks.GenericIPBlockingTask.GetTempBanVictims()
   en EvlWatcher.EvlWatcher.Run()
```

In affected servers this log is found every 30/31 seconds.

**Comment by devnulli** [comment]
thank you! i finally have the stacktrace so i can remove this bastard. will fix that today

**Comment by devnulli** [comment]
![image](https://github.com/devnulli/EvlWatcher/assets/3720480/276f36d8-ad0d-4eb0-9fe4-da7dcd4022eb)
there it is, it was there all the way , i just didnt see it

**Comment by devnulli** [comment]
closing this now
