### ISSUE TITLE
ip banned count

### ISSUE THREAD

**Issue by redquantum** [devnulli/EvlWatcher#127]
Hello Dear Friend,

I want to ban it directly if there is an ip that makes a false login or attack even once. How can I do this? I want to directly ban every attack or false login to the rdp port without any option. I want to give the right to try a maximum of 1-2 times. How can I set this?

Thank you.

**Comment by devnulli** [comment]
Hi, you can't do that in EvlWatcher. Its based on event logs and normally checks them every 30 seconds. What you can do is manipulating the default config to check that more often, but i do not recommend that. The default settings  give you pretty restrictive RDP options already . Beyond that, you would need to use a different software.
