### ISSUE TITLE
Polling old events

### ISSUE THREAD

**Issue by AvrumFeldman** [devnulli/EvlWatcher#130]
Seems EvlWatcher is polling the same event logs over and over causing constant bans. (Causes Event floods in the event logs for IP addresses I removed from temp ban list).

I recently updated the timezone on the server but EvlWatcher is still reporting the old timezone, is it possible this is the cause?

Edit: I can confirm it's not TimeZone, I reinstalled EvlWatcher and the time shows correctly now, but still parsing the same old events.

**Comment by AvrumFeldman** [comment]
Update: Issue seems to self resolve. Is there any way I can look into this further to identify what caused this?

**Comment by devnulli** [comment]
if a reinstall solved it it was probably a mistake in the configuration file,  (i.e timeframe too big)
could also have been a discrepancy between server time and event log time
