### ISSUE TITLE
Love to help/test

### ISSUE THREAD

**Issue by JReming85** [devnulli/EvlWatcher#14]
Would love to help beta test, I can potentially provide a small test server for you as well.

As far as help coding, I am not the greatest when it comes to windows but once I have more free time (crazy time at work) I would be more then willing to give it a shot.

**Comment by devnulli** [comment]
Hi, that would be extremely helpful, thanks! Can I come back to you in a while (when its mostly done and a new installer is ready), so you could try it out on a Windows Server (which is exposed to the web with RDO on 3389 port open).

Might take a while, though. (end of May - beginning of June..ish)

**Comment by gustavorlopez** [comment]
Hi, I could help too. With Windows Server 2012 R2 and Server 2016.

**Comment by gustavorlopez** [comment]
Hi, what happened with the new version ?

**Comment by JReming85** [comment]
Most likely he is still working on it or has other obligations due to the pandemic effecting us all.

Be patient, he will pull when its done

**Comment by devnulli** [comment]
Hi, I am already on it, but it will take some more days..

**Comment by devnulli** [comment]
Hi, so sorry again for the DELAYS guys, the new version will be out in JUNE, I really really really promise..  and while that goddamn corona thingy would be a good excuse, its more that i was locked up at home for WEEKS and STILL didnt do it. so it's kindof an anti-excuse.. :)

**Comment by gustavorlopez** [comment]
Hi, June is ok for me.

**Comment by myscreenname** [comment]
I'm game to test as well.

**Comment by devnulli** [comment]
is almost done..

**Comment by devnulli** [comment]
@shimuldn

**Comment by devnulli** [comment]
Hi guys. Please have a look at the first beta. Actually, it should not change much on the outside, but it changed a lot on the inside.
After that works, i will move on the the console and what not.

Thanks again for your support,

Mike

**Comment by shimuldn** [comment]
Testing on one VM

**Comment by NukeDev** [comment]
Testing on 3 servers, i'm interested to help this project too! (with some evening coding). 
@devnulli let's have a talk?

Jimmy

**Comment by devnulli** [comment]
Hi Jimmy, that would be great, thanks.

Be aware that on saturday there will be the beta2, which also needs testing (its got the console and ui things) .

Im glad to get help, for I don't even have Windows Servers anymore and thus a complete unability to test it (can test the ui and all, but not the actual banning)  😅 .

So:

- Right now im finishing the beta2, which should be finished by friday. if you want, i can take you on board after its done, and show you around in the code a bit.

- also, im working in #9 so people can contribute easily and without my consultation

**Comment by shimuldn** [comment]
About 36 hours of beta testing.

1IP blocked.
<img width="573" alt="Screenshot 2020-11-04 at 1 21 55 PM" src="https://user-images.githubusercontent.com/12117121/98083846-f6d9c680-1ea0-11eb-924a-bf752c0afad3.png">

**Comment by devnulli** [comment]
@shimuldn  ok thanks, please keep me updated, im still searching for the memory leak (suspecting firewall API). if i cant find it, maybe we need to dump the memory of the process to find it.  i'll get back to you in some hours.. please, dont restart it, let it eat up..

**Comment by devnulli** [comment]
@shimuldn thanks for your test. i think i found the problem. please wait, while i create a new beta1 version to test.

**Comment by shimuldn** [comment]
@devnulli 
Okey. Current ram usages are 137MB. So it's increasing.
Also, another issue with the last version is blocking. Blocking didn't work properly. I just fixed another server by doing a few reboots.

<img width="334" alt="Screenshot 2020-11-04 at 4 32 17 PM" src="https://user-images.githubusercontent.com/12117121/98103693-665caf80-1ebb-11eb-9066-4695391565be.png">

Spammers are trying to crack the password by doing Brute-force attack.
<img width="975" alt="Screenshot 2020-11-04 at 4 38 08 PM" src="https://user-images.githubusercontent.com/12117121/98104233-28ac5680-1ebc-11eb-89eb-0db29793e866.png">

I can provide you logs if needed.
If you need a windows server for testing you may signup for GCP or any other cloud trial. If not in this case i may help you to get access.

**Comment by devnulli** [comment]
hi, i put at into a separate issue

**Comment by devnulli** [comment]
hi, im closing that -> convo moved to the pull request anyway
