### ISSUE TITLE
Share your Patreon or other profile so we can support the project

### ISSUE THREAD

**Issue by Balls0fSteel** [devnulli/EvlWatcher#16]
I love EvlWatcher and been using it for several years at this point. Please, add a way so we can support the project. I'd recommend adding multiple ways.

- Patreon (monthly subscription/support)
- Paypal (for direct donation)
- Bitcoin/other coin wallet addresses (for crypto)

There is a thing called "Open Collective" but I don't think it's the tool for this project.
Thank you for your hard work. Also, please add the old binaries somewhere.

**Comment by devnulli** [comment]
Hi, you can find the old binaries [here](https://github.com/devnulli/EvlWatcher/tree/master/Versions)

Also thanks for offering to support me. I'll post a patreon profile in the README.md.. as soon as i finished the new release that I promised .. ... dont bother downloading an old version.. the new one is gonna be out in June, that I promise.

**Comment by Balls0fSteel** [comment]
Haha it's fine, I just installed the 2.0 alpha on a bunch of PCs. Long story short, it was the best option (having open RDP Win10 Pro machines on the internet). I'll watch the project, and the README then... 👀 

Thank you for getting back and sorry for using up a ticket for this.

**Comment by devnulli** [comment]
Hi @Balls0fSteel, after thinking about it, I won't do that Patreon thing. It's just.. 

What i have done is to post a bitcoin address for ppl who want to buy me a 🍺 / ☕  in the [README.md](https://github.com/devnulli/EvlWatcher/blob/master/README.md#if-you-want-to-support-evlwatcher-monetarily).

 Or you can just choose a local charity and donate to it. 

closing this now, and THANKS for the issue.

**Comment by Balls0fSteel** [comment]
There is also Ko-Fi. But I'll look into BTC. The only reason I hate it is because its SO HARD to get BTC. You want to give 10$? Prepare yourself to lose 30$ in currency conversion, SEPA transfer, etc. It sucks so so so much. 😢

**Comment by devnulli** [comment]
thats true, practically, it sucks.  but in your heart you like it. its hackery and cool and has that shady feeling somewhat ahha

seriously: i have never heard of ko-fi, will look into that. also will look into buy-me-coffe.com or something like that i heard of

**Comment by Balls0fSteel** [comment]
I didn't hear about the latter, only ko-fi. It's just like "throw me some money". Anyhow, I'll check. Wish you could still mine buttcoins, then it'd be easier, ha.

**Comment by devnulli** [comment]
hm ko-fi and buymeacoffe.com seems to need paypal, which sucks. i dumped them after the wau-holland thing.. :cry:

**Comment by Balls0fSteel** [comment]
Ok just give us Paypal then. Check it by donating to yourself (what info is visible, etc.) Yes, you will have to pay taxes after it. But who knows, you may lose out on 500-5000$ or whatever. Some people just don't want to mess with BTC. :(

**Comment by devnulli** [comment]
jup.

**Comment by devnulli** [comment]
sheesh.. its pretty hard to get something simple like a beer paid.. haha

**Comment by Balls0fSteel** [comment]
I pay you a beer if you add it. 🍺

**Comment by devnulli** [comment]
haha deal.

**Comment by devnulli** [comment]
done,, ok i admit wasnt that hard..   <a href='https://ko-fi.com/F2F02MKY9' target='_blank'><img height='36' style='border:0px;height:36px;' src='https://cdn.ko-fi.com/cdn/kofi2.png?v=2' border='0' alt='Buy Me a Coffee at ko-fi.com' /></a>

thanks man!

**Comment by Balls0fSteel** [comment]
nah. thank **YOU**, for this great software.
sorry for taking up so much of your time with this ticket. good luck with v2.0, eagerly waiting, lol.

**Comment by devnulli** [comment]
thanks, we are pretty much done, only the rule editor is still missing ;)

![image](https://user-images.githubusercontent.com/3720480/98453227-287bb780-2157-11eb-9b90-6f773c8a8005.png)
![image](https://user-images.githubusercontent.com/3720480/98453230-34677980-2157-11eb-9979-4e2b92f357de.png)

**Comment by Balls0fSteel** [comment]
Those images in the menus, lmao, I legit laughed out loud. 10/10.
