### ISSUE TITLE
[v1.4] Using not standard port doesnt block

### ISSUE THREAD

**Issue by meigallodixital** [devnulli/EvlWatcher#17]
We are using a non-standard port for RDP. When we enter wrong passwords (+5) it doesn't ban us temporarily. Would something have to be configured for this case?

**Enviroment:** Windows 10 professional 1909 and windows 10 professional 2004. EvlWatcher version 1.4 in both.

**Comment by devnulli** [comment]
hi, could you find the entry in the windows event log that should trigger the block and post it here? thx
