### ISSUE TITLE
Huge ram usage

### ISSUE THREAD

**Issue by shimuldn** [devnulli/EvlWatcher#18]
EvlWatcher-v2.0 alpha Using too much ram after some days of 24/7 server running.

I see the server using the full ram around 6 GB. After a reboot, it goes back to normal. Happen on my 2 servers 2019.
On Task Manager I see Cached almost all the ram server had.

<img width="535" alt="Screenshot" src="https://user-images.githubusercontent.com/12117121/89576538-0cf9cb80-d84d-11ea-8110-969f139801c7.png">

**Comment by shimuldn** [comment]
The fix i am using is stop and start the service everyday using "Task Scheduler"

**Comment by devnulli** [comment]
there is a problem with the protocol, which gets bigger as evlwatcher runs

**Comment by s7646984** [comment]
Ran into the same issue on Server 2019
Create the following batch script and run daily. Would be good if there was a warning or the home page or ability for the service to restart itself if it could detect it was growing past a normal limit.

NET STOP "EvlWatcher"
NET START "EvlWatcher"

**Comment by shimuldn** [comment]
> NET STOP "EvlWatcher"
> NET START "EvlWatcher"

That's what i am doing using `Task Scheduler`

**Comment by devnulli** [comment]
this should be fixed in 2.0 beta

**Comment by devnulli** [comment]
the memory leak is not in the firewall api, its in the event log records.
