### ISSUE TITLE
4625 Event not Blocking

### ISSUE THREAD

**Issue by devnulli** [devnulli/EvlWatcher#21]
Spammers are trying to crack the password by doing Brute-force attack.
<img width="975" alt="Screenshot 2020-11-04 at 4 38 08 PM" src="https://user-images.githubusercontent.com/12117121/98104233-28ac5680-1ebc-11eb-89eb-0db29793e866.png">

I can provide you logs if needed.
If you need a windows server for testing you may signup for GCP or any other cloud trial. If not in this case i may help you to get access.

Blocking needs to improve.

_Originally posted by @shimuldn in https://github.com/devnulli/EvlWatcher/issues/14#issuecomment-721670584_

**Comment by devnulli** [comment]
@shimuldn: Is there any way Evlwatcher could find an IP for these attempts? (either directly in the XML, or by using a related event?) otherwise there is no way EvlWatcher (or any other Event-Log-Based IDS) can block that

![image](https://user-images.githubusercontent.com/3720480/98107175-67c9b000-1e9a-11eb-9add-47488427a7a0.png)

**Comment by shimuldn** [comment]
@devnulli 
Here you go

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event"> 
- <System> 
<EventID>4625</EventID> 
<Version>0</Version> 
<Level>0</Level> 
...
....
<Data Name="LogonProcessName">User32</Data> 
<Data Name="AuthenticationPackageName">Negotiate</Data> 
<Data Name="WorkstationName">INSTANCE-202010</Data> 
<Data Name="TransmittedServices">-</Data> 
<Data Name="LmPackageName">-</Data> 
<Data Name="KeyLength">0</Data> 
<Data Name="ProcessId">0x7bc</Data> 
<Data Name="ProcessName">C:\Windows\System32\svchost.exe</Data> 
<Data Name="IpAddress">45.129.33.203</Data> 
<Data Name="IpPort">0</Data> 
</EventData> 
</Event>

**Comment by shimuldn** [comment]
@devnulli 
Every other log on the below screenshot has the same IP address.
<img width="968" alt="Screenshot 2020-11-04 at 5 18 08 PM" src="https://user-images.githubusercontent.com/12117121/98108430-f00f7b80-1ec1-11eb-8ee5-8f7d0983667e.png">

But the bad news is the `Evlwatcher` not blocking the IP address.
<img width="828" alt="Screenshot 2020-11-04 at 5 19 22 PM" src="https://user-images.githubusercontent.com/12117121/98108627-4977aa80-1ec2-11eb-8c40-22341b7953e1.png">

**Comment by devnulli** [comment]
hi, could you change the config.xml in line 68 to: `&lt;Data Name=".IpAddress."&gt;(\d*.\d*.\d*.\d*)`, and retry? thanks


![image](https://user-images.githubusercontent.com/3720480/98109046-3acacc80-1e9d-11eb-89fb-9ed8b7581a25.png)

**Comment by devnulli** [comment]
hi, could you change line 68 in config.xml to  `  &lt;Data Name=.IpAddress.&gt;(\d*.\d*.\d*.\d*)`
![image](https://user-images.githubusercontent.com/3720480/98109338-b298f700-1e9d-11eb-86a1-005c9d34c044.png)

and retry?

**Comment by shimuldn** [comment]
@devnulli on it will update

**Comment by shimuldn** [comment]
@devnulli Batter than before i think. Will update again

**Comment by shimuldn** [comment]
Found some weird behavior Within 1 hour 20 minutes got 242 log event 4625. All from the same IP but the wired thing is `EvlWatcher` didn't block the IP. The IP found on the firewall is different.

For this 1 hour 20 minutes the attack was constant.

<img width="1213" alt="Screenshot 2020-11-05 at 1 04 29 PM" src="https://user-images.githubusercontent.com/12117121/98212474-a9755c00-1f69-11eb-81f4-17bb6f885022.png">
<img width="1432" alt="Screenshot 2020-11-05 at 1 05 36 PM" src="https://user-images.githubusercontent.com/12117121/98212481-abd7b600-1f69-11eb-87e0-f56a91be5c37.png">
<img width="1211" alt="Screenshot 2020-11-05 at 1 10 46 PM" src="https://user-images.githubusercontent.com/12117121/98212496-af6b3d00-1f69-11eb-803d-2c8a13ace0c8.png">

**Comment by devnulli** [comment]
hi, can you post the xml again please, i will look into that.

**Comment by devnulli** [comment]
im not sure if that is a glitch when we created the beta version.
i have created a clean new version. does the problem persist in that version ?

[Clean Beta](https://github.com/devnulli/EvlWatcher/blob/v2-beta1/Versions/v2/EvlWatcher-v2.0%20beta%201-setup.exe)

**Comment by devnulli** [comment]
@shimuldn  does it work or should i look deeper into it?

**Comment by devnulli** [comment]
pull request was closed. if it still occurs, create a new issue please. thx

**Comment by shimuldn** [comment]
Checking RDPs now
