### ISSUE TITLE
Windows Defender (and a few other heuristics) actually think we're a virus.

### ISSUE THREAD

**Issue by devnulli** [devnulli/EvlWatcher#32]
Great, well, now obviously, windows defender thinks we are a virus.
Well, we are not windows defender, but we are defending windows! (joke)

So, what can we do about that.. do we need a signed app?

**Comment by shimuldn** [comment]
Crap.

Signin will be great but there is no free option available.
The minimum I can find €25.00 https://www.certum.eu/en/code-signing-certificates/

**Comment by devnulli** [comment]
yea, looks like we need to sign the release.

**Comment by devnulli** [comment]
ok, so while i absolutely understand the necessity to sign EvlWatcher 2.0, (being written in c# its easily changeable and could be used badly, especially because it runs as service) but it hurts.  why? because

oh man.. so   💸 💸 there go the 12€ donation money i got so far for EvlWatcher, and i can finally pay for EvlWatcher to be downloadable. 😠  as far is i know an extended EV somewhere well over 200€/year --- 

and to be honest, that makes it really hard for small beneficial services to be maintained.. its a big kick in the balls of open source.  i'll think about that a week or so and come up with what i'll do (self sign/buy it/not fixing it and publishing checksum/...)

**Comment by devnulli** [comment]
While I'm waiting until EvlWatcher can afford a certificate, i suggest the following workaround

**Its pretty sure not a virus, when you make sure of the following:**

- only download it from here (github)

If you download it from somewhere else:

- check its MD5
   - for v2.0 the MD5 is `d658718ea9cc794e704b02b7c252365e`
   - to check an MD5 an windows, type `CertUtil -hashfile "EvlWatcher-v2.0 setup.exe" MD5`

EvlWatcher 2.0 is written in C# and therefore easily readable and changeable. 
So is it a virus when you didnt make sure of the above steps? Possibly, yea. Probably not, but possibly.

**Comment by devnulli** [comment]
Hi,

the new release has been signed, and we did a submissal to Microsoft Smart Screen, to report the false positive.
It will take a time for the certificate to gain trust, so i will leave that open to check back in a while.

It looks much better now though, I am certain that we will stop being a "virus" in some days

![image](https://user-images.githubusercontent.com/3720480/105641561-dc523080-5e84-11eb-98d7-89800b04d983.png)

**Comment by shimuldn** [comment]
What is the status of the certificate?

**Comment by shimuldn** [comment]
Wow, hoping for stupid MS will fix soon.

**Comment by devnulli** [comment]
To be honest.. they aren't SO stupid. It's okay to block unsigned code 😄 . But I will start calling them stupid if they still think we're a virus in one or two weekd 😁

**Comment by devnulli** [comment]
i no longer get virus warnings, and would close this now.

@shimuldn , do you get any download warnings?

**Comment by shimuldn** [comment]
@devnulli 
Nope! Not a virus anymore! And developer verified :) thanks to 6 donner.
Good job.


<img width="477" alt="Screenshot 2021-01-26 at 12 02 05 AM" src="https://user-images.githubusercontent.com/12117121/105749734-d41ff100-5f69-11eb-9667-c7811515c43a.png">
