### ISSUE TITLE
Active="false" property ignored for tasks

### ISSUE THREAD

**Issue by fernadie** [devnulli/EvlWatcher#34]
Rules still run after restarting service, regardless of "Active" setting in config.xml.
Workaround: backup config.xml and delete Task.

**Comment by devnulli** [comment]
can validate. 
![image](https://user-images.githubusercontent.com/3720480/101823104-95a1b480-3b2a-11eb-8a2f-239348d1afba.png)

results in:
![image](https://user-images.githubusercontent.com/3720480/101823142-a05c4980-3b2a-11eb-8fe6-7f1b4be8c1a2.png)

**Comment by devnulli** [comment]
problem found and fixed
![image](https://user-images.githubusercontent.com/3720480/101823721-7eaf9200-3b2b-11eb-9b86-92455a44cd7e.png)

**Comment by devnulli** [comment]
have tested it, and in the corrected version, the disabled tasks did not run
