### ISSUE TITLE
Hey everyone, please provide us with samples, so we could support more default protocols, like FTP, MYSQL, and whatnot

### ISSUE THREAD

**Issue by devnulli** [devnulli/EvlWatcher#36]

**Comment by snblackout** [comment]
Could you even potentially support custom IP reporting?  Possibly EvlWatcher could scan the local database for entries that have been added from other services, like WebAPI that has detection if IP is trying to brute it's way, it could add entries into the database table, then EvlWatcher could occasionally scan that table for increases in the count of the trouble IP and act on it?

By the way, I just found your solution.  Sucks regarding the Windows Defender, I had to allow the setup program to get it installed and even just to allow the file to remain to do the MD5 scan on it.  I'm hoping to test this more and send some money your way for your hard work.  I always saw the Failed Audit entries in the event log for RDP and didn't know what to do, thought of writing my own, but look you did it! 👍

**Comment by devnulli** [comment]
i've got a question about the custom reporting, yea, i can add that no problem, but it would be nicer if the webapi would just dump events to the eventlog. if that was the case, it would just be a new task in the config.xml . if thats not possible, i guess i could add additional sources like databases or even apis.

about that windows defender  - you're right it really sucks. ill have to sign it.

**Comment by JReming85** [comment]
I dont have those services running but maybe you can get some help from cyberarm's abandoned project https://github.com/EFTEC/Cyberarms

Also as I offered long ago, if you need a test server I can provide a small windows server for you to use (VM running on one of my other servers w/ its own IP)

**Comment by peyman47** [comment]
sql server 1433 port would be great

**Comment by xcjs** [comment]
@brighthorizon A while ago I added SSH support, which should at least cover SFTP.

**Comment by devnulli** [comment]
im closing this generic issue
