### ISSUE TITLE
report found IPs and there occurence count in log 

### ISSUE THREAD

**Issue by devnulli** [devnulli/EvlWatcher#38]
Having some reporting in the logs or some way to track a certain IP better over time would be better. 
_Originally posted by @snblackout in https://github.com/devnulli/EvlWatcher/issues/37#issuecomment-757345607_

**Comment by snblackout** [comment]
Just providing some information. I downloaded source, compiled and deployed.  I see the extra reporting.  Below is the output of an IP that is found by multiple configurations it seems, but is not in the temporary banned list in the console.

```
1/23/2021 13:05:32 - [Info]: BlockRDPBrutersByRdpCore131: found 89.248.165.20, trigger count is 1
1/23/2021 13:06:02 - [Info]: BlockRDPBrutersBySecurity4625: found 89.248.165.20, trigger count is 1
1/23/2021 13:06:02 - [Info]: BlockRDPBrutersBySecurity4625: found 89.248.165.20, trigger count is 2
1/23/2021 13:06:02 - [Info]: BlockRDPBrutersByRdpCore140: found 89.248.165.20, trigger count is 1
1/23/2021 13:06:02 - [Info]: BlockRDPBrutersByRdpCore140: found 89.248.165.20, trigger count is 2
1/23/2021 13:06:02 - [Info]: BlockRDPBrutersByRdpCore131: found 89.248.165.20, trigger count is 1
1/23/2021 13:06:02 - [Info]: BlockRDPBrutersByRdpCore131: found 89.248.165.20, trigger count is 2
1/23/2021 13:06:32 - [Info]: BlockRDPBrutersBySecurity4625: found 89.248.165.20, trigger count is 1
1/23/2021 13:06:32 - [Info]: BlockRDPBrutersByRdpCore140: found 89.248.165.20, trigger count is 1
1/23/2021 13:06:32 - [Info]: BlockRDPBrutersByRdpCore131: found 89.248.165.20, trigger count is 1
1/23/2021 13:07:02 - [Info]: BlockRDPBrutersBySecurity4625: found 89.248.165.20, trigger count is 1
1/23/2021 13:07:02 - [Info]: BlockRDPBrutersByRdpCore140: found 89.248.165.20, trigger count is 1
1/23/2021 13:07:02 - [Info]: BlockRDPBrutersByRdpCore140: found 89.248.165.20, trigger count is 2
1/23/2021 13:07:02 - [Info]: BlockRDPBrutersByRdpCore131: found 89.248.165.20, trigger count is 1
1/23/2021 13:07:02 - [Info]: BlockRDPBrutersByRdpCore131: found 89.248.165.20, trigger count is 2
1/23/2021 13:07:32 - [Info]: BlockRDPBrutersBySecurity4625: found 89.248.165.20, trigger count is 1
1/23/2021 13:07:32 - [Info]: BlockRDPBrutersBySecurity4625: found 89.248.165.20, trigger count is 2
1/23/2021 13:07:32 - [Info]: BlockRDPBrutersByRdpCore140: found 89.248.165.20, trigger count is 1
1/23/2021 13:07:32 - [Info]: BlockRDPBrutersByRdpCore140: found 89.248.165.20, trigger count is 2
1/23/2021 13:07:32 - [Info]: BlockRDPBrutersByRdpCore131: found 89.248.165.20, trigger count is 1
1/23/2021 13:07:32 - [Info]: BlockRDPBrutersByRdpCore131: found 89.248.165.20, trigger count is 2
```

I see a "trigger count is X" and also "this is strike X".  What does these two mean exactly?

`Banning 193.93.62.73, this is strike 3`

Also looks like you're logging the type and not the value here:

Banned 3 (strike count was over System.Collections.Generic.Dictionary`2[System.Net.IPAddress,System.Int32]

Thanks for the update.

**Comment by devnulli** [comment]
about your question:
this is about how its meant to be:

trigger count : when the eventlog is scanned, there is a timeframe that is analysed (for instance, 2 minutes).
whenever someone generated more than <triggercount> logentry in these <triggercount> minutes, it comes to a ban.

![image](https://user-images.githubusercontent.com/3720480/105627336-a5552e00-5e36-11eb-9a1f-45f7fb240e27.png)

strike:
whenever someone is banned because he tried to often in a certain time, the service temporarily bans the attacker for some hours and this is a strike.  evlwatcher counts this in memory, so restarting the service or whatever resets the strike conter

![image](https://user-images.githubusercontent.com/3720480/105627618-2bbe3f80-5e38-11eb-8f85-1d1a6bf1d413.png)


so:
*trigger count* : counting the log entries of the same ip in the analyzed time frame
*strike*: getting a temporary ban

with a normal setting, and a machine attacking your rdp, the ip will enter the permanent ban list after about 3h of brute forcing, while having the machine reachable for about 0-90 seconds.

00:00:00  attacker starts brute force
00:00:30 attacker will be temp banned around that time (strike 1)

- machine is unreachable 1h

02:00:30 - ban is lifted, machine comes back - attacker keeps trying
02:01:00 - attacker will be banned a second time about now (strike 2)

- machine is unreachable for 1 h

04:01:00 - ban is lifted, machine comes back - attacker STILL keeps trying
04:01:30 - attacker will be banned forever (strike 3)

**Comment by devnulli** [comment]
setting the permanent ban crashes because service checks for client privileges

**Comment by devnulli** [comment]
@snblackout  - thanks for your info, thanks to you we have fixed a bug that would prevent evlwatcher from permanently banning IPS. 

just to make sure, do you have an message like "object reference not set to an instance" in your eventlog at the time the permanent ban would have beend set?
![image](https://user-images.githubusercontent.com/3720480/105629201-ed2d8280-5e41-11eb-999f-976871ede3b8.png)

**Comment by snblackout** [comment]
Yes i was seeing that error in the event logs.  There was no stack trace attached so it really didn't point me anywhere.  Glad my info has helped!
