### ISSUE TITLE
A shortcut on Start Menu

### ISSUE THREAD

**Issue by shimuldn** [devnulli/EvlWatcher#42]
Have to go to `C:\Program Files (x86)\EvlWatcher` to find the console app.
A shortcut on Startmenu also on Desktop will make this software user-friendly for normal users.

Adding on the Desktop can be optional.
It's a matter of 3 clicks adding the shortcut on Desktop for us but some users may struggle a little bit.

Again it's a less priority feature so take your time.

Thank you for making the Internet safe a little bit.
Thank you for your time.

**Comment by devnulli** [comment]
I dont know about the Desktop link (need to switch context from admin to current user somehow), but we can definitely do the start menu thing.
I'll look into it following [that](https://nsis.sourceforge.io/mediawiki/index.php?title=A_simple_installer_with_start_menu_shortcut_and_uninstaller&oldid=21654) guide here.

**Comment by shimuldn** [comment]
Only the Start menu will work.
The desktop shortcut is not necessary. It's just my thought for non-technical users.

**Comment by devnulli** [comment]
![image](https://user-images.githubusercontent.com/3720480/106369345-f7271800-6350-11eb-944a-f8dff4fd4f4c.png)

**Comment by shimuldn** [comment]
Wow. Thank you
