### ISSUE TITLE
Feature: Remove IP from temporary banned list

### ISSUE THREAD

**Issue by dt64** [devnulli/EvlWatcher#45]
currently if an IP is on the temporarily banned list it can be transferred to permanently banned list and white-listed IP list only. In a world on dynamic IP addresses this is unfortunate. If the temporarily banned IP list includes a false positive this IP needs to be permanently whitelisted where the admin probably wants to just remove it from the temporarily banned IP list instead.

Therefore it would be great to have an additional button underneath the "temporarily banned IPs" list to just remove the selected IP(s) from it.

**Comment by devnulli** [comment]
I think we can do that.

**Comment by devnulli** [comment]
will be in the next release
