### ISSUE TITLE
High trigger count without ban.

### ISSUE THREAD

**Issue by devnulli** [devnulli/EvlWatcher#46]
I did notice going through, some have a very high trigger count.  Looking at the console, that IP is not in the temp or perma banned.  Interesting.

`BlockRDPBrutersBySecurity4625: found 186.96.174.85, trigger count is 376`

_Originally posted by @snblackout in https://github.com/devnulli/EvlWatcher/issues/44#issuecomment-767907144_

**Comment by devnulli** [comment]
`BlockRDPBrutersBySecurity4625: found 186.96.174.85, trigger count is 376` thats interesting. that should definitely get a perma ban, unless its whitelisted. could you keep an eye on that?  

thx

**Comment by snblackout** [comment]
I'll keep a look out, but that IP is not in any events when I search now as old events got purged.  Strange.  Will try to find more with high trigger counts that aren't being temp banned.

**Comment by snblackout** [comment]
Found another IP that is being weird with high trigger count, but this one made it to the temporary ban.  But still had event logs come in after that.  Maybe a carryover of logs scanned from previous?  Also, when you temp/perma ban an IP, there might be a chance you'll pick up more invalid event logs after that just from the time it took to create/update the firewall entry?  Just a thought.

Check out my attached event log for that one IP I just noticed.

[export1-190-232-27-219.zip](https://github.com/devnulli/EvlWatcher/files/5883844/export1-190-232-27-219.zip)

**Comment by devnulli** [comment]
hi, that seems okay, when i read that correctly, the ip was already banned, but past log entries were put to analyze again.
this is the case, because the event-age is normally 2 minutes, so all events from the past 2 minutes are routed to the task, while the task is executed every 30 seconds or so. -  im closing this
