### ISSUE TITLE
Dark Mode and NS Lookup feature requests

### ISSUE THREAD

**Issue by debpalash** [devnulli/EvlWatcher#48]
Really a good sofware, my RDP's was constantly brute-forced by random IP's and often i couldn't login to them.
I have some improvement/feature requests. 

- _**Local ip list backup/sync with software updates/reinstall [ Urgent] EDIT: was moved to own issue**_
- Dark mode
- IP whois/region info either by third party or implemented inside app

Thanks @shimuldn for suggestion to use this.

**Comment by shimuldn** [comment]
Permanent Ban list auto backup & restore is required for an upgrade or reinstall.

**Comment by devnulli** [comment]
Yeah losing the ban list as well as custom tasks when upgrading is a true issue

**Comment by debpalash** [comment]
@devnulli so the ban/temp list get saved in readable files?

**Comment by devnulli** [comment]
i have separated the issue that you lose lists from the other feature requests 
its now in  #53
