### ISSUE TITLE
Update management

### ISSUE THREAD

**Issue by shimuldn** [devnulli/EvlWatcher#49]
Future plan:
Auto-update the software or an option to check the update available, click to download and install or something similar for a better user experience.

**Comment by devnulli** [comment]
auto updates: i would rather not do that. right now, the service runs a localservice (not as localnetwork), meaning it can guarantee every admin, that it will never, under no circumstances communicate (external or internal) over the network.

maybe updating via the console app, that could be an option. - 
we could look into that, but not in the close future - but lets keep it a feature request. - who knows 😁

**Comment by shimuldn** [comment]
Auto-updates: Good point, I agree.


Yeah, who knows. Let's where the apps go!

**Comment by peyman47** [comment]
sql server port 1433 would be great if supported

**Comment by Sparticuz** [comment]
@shimuldn This is how I am managing updates for EvlWatcher. (Also how I install it initially across my domain) I put this script on my GPO->Computer Config->Windows Settings->Scripts->Startup and it checks if EvlWatcher is installed, and if it's out of date. To update EvlWatcher, I put the exe in the correct spot, then update the `$version -eq 2.1.5.0` to be the correct version

```posh
$DefaultLogLocation = "C:\Windows\Logs\EvlWatcher.txt"
Start-Transcript -Path $DefaultLogLocation

Write-Host "Starting EvlWatcher Install"

If( -not(Test-Path "C:\Program Files (x86)\EvlWatcher" )) {
    Write-Host "EvlWatcher not installed, starting install process..."
    $params = @(
        '/S'
    )
    $p = Start-Process 'MYDOMAINSYSVOL\Software\EvlWatcher\EvlWatcher-v2.1.5-setup.exe' -ArgumentList $params -NoNewWindow -Wait -PassThru
    $p.ExitCode
    Write-Host "Done Installing EvlWatcher $($p.ExitCode)"
} else {
    Write-Host "EvlWatcher already installed, checking version"
    $version = (Get-ItemProperty "C:\Program Files (x86)\EvlWatcher\EvlWatcher.exe").VersionInfo.ProductVersion
    If( $version -eq 2.1.5.0) {
        Write-Host "The latest version of EvlWatcher is already installed, no changes have been made."
    } else {
        Write-Host "An outdated version of EvlWatcher is installed, updating..."
        $params = @(
            '/S'
        )
        $p = Start-Process '\\MYDOMAINSYSVOL\Software\EvlWatcher\EvlWatcher-v2.1.5-setup.exe' -ArgumentList $params -NoNewWindow -Wait -PassThru
        $p.ExitCode
        Write-Host "Done Updating EvlWatcher $($p.ExitCode)"
    }
}

Stop-Transcript
```
