### ISSUE TITLE
add ssh protocol support

### ISSUE THREAD

**Issue by Artym1** [devnulli/EvlWatcher#52]
This can be quite useful. Thanks for the great work.

**Comment by shimuldn** [comment]
@Artym1 Can you describe what you're looking for?

**Comment by devnulli** [comment]
@Artym1 If you Can provide us a Sample from the Windows event log (provoke a failed login and find the event log entry), we will gladly add it instantly.

If theres a different kind of logging in place, (file based or whatever) just provide that instead. 

Thx

**Comment by devnulli** [comment]
openssh support is not provided
