### ISSUE TITLE
Change image options in console?

### ISSUE THREAD

**Issue by deepdvd** [devnulli/EvlWatcher#57]
Thanks for all your hard work on this project. I love it!  Except one thing.

Maybe it's just me, but when I open the console, it feels like I'm being flipped off.  I know it's meant for the hackers, but could we add an option to customize the background images?  Or even just replace the image with a cross-out symbol like this:
https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/ProhibitionSign2.svg/1200px-ProhibitionSign2.svg.png

I also don't want to have to look over my shoulder to see if my kids are watching when I open the console. 
Thanks in advance.

**Comment by devnulli** [comment]
i have now replaced that image with a the "safe for work" image. i did not create an option for that, as that would create extra complexity just for coolness, which is not the point . So:

![image](https://user-images.githubusercontent.com/3720480/115160588-4bf94580-a099-11eb-8be2-8b844e8f68d4.png)
