### ISSUE TITLE
Add all temporary to permanent

### ISSUE THREAD

**Issue by didyouexpectthat** [devnulli/EvlWatcher#58]
I multi-select temp banned IPs and click the 'lock' for each IP to permanently ban it. It would be cool if:

- When multi-selected, add all temporary IPs to permanent IPs at once (not having to click the lock for each selected IP), or
- An "Add all" button to add all temporary IPs to the permanent list without selecting any. 

Sometimes I have a lot of temp banned IPs and I want to bulk-add them all and get on with life.  Thank you for the consideration.

**Comment by devnulli** [comment]
Seems a good idea
