### ISSUE TITLE
Windows 2008 R2 missing event log 

### ISSUE THREAD

**Issue by did-vmonroig** [devnulli/EvlWatcher#59]
In this ancient operating system EvlWatcher throws an error every 30 seconds in Live tab, trying to look for a non existing event log:

`12/04/2021 13:08:01 - [Error]: Event Log Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational was not found, tasks that require these events will not work`

Seems that Windows 2008 R2 needs another ruleset to work properly.

**Comment by pelosuki** [comment]
Worked fine for a few days, but now I`m having the same problem, Windows 2008 R2 as well.

Others Windows versions looks tha works fine

**Comment by devnulli** [comment]
I can't fix that missing event source. When it's not provided by the OS, it's not there. But if you find any events that ARE there and could identify IP-bruters , but are not yet known to EvlWatcher on 2008 R2, please post them.

**Comment by devnulli** [comment]
Waiting if any new Events are provided before closing that.
