### ISSUE TITLE
App crash: "AddressAlreadyInUseException"

### ISSUE THREAD

**Issue by campbellkerr** [devnulli/EvlWatcher#63]
Fresh install (win7), attempted to open the GUI and it crashed. Service is running. Couldn't find any quick/obvious fixes on google. Any ideas? Cheers

![image](https://user-images.githubusercontent.com/38451588/115978428-ac6d1300-a5c2-11eb-8782-df273c912529.png)

**Comment by devnulli** [comment]
You are attempting to run the service executable. (which always runs in background).,
To open the console, run EvlWatcherConsole.exe

**Comment by devnulli** [comment]
i admit its misleading xe names tho :)
