### ISSUE TITLE
White-listed IPs are not banned, but they ARE displayed in the ban list when found - behaviour is misleading

### ISSUE THREAD

**Issue by FranticOrange** [devnulli/EvlWatcher#64]
192.168.* is present in the white-listed IP patterns but some IPs on the local network are added to the banned lists, e.g. 192.168.1.230. Adding 192.168.1.* to the white-list doesn't resolve this either. Removing the banned IPs from the list only results in them being added again at some future point.

**Comment by FranticOrange** [comment]
An update to the above: IP addresses that match the white-listed patterns are **not** added to the firewall rule, but they **are** added to the internal ban list. This is what was misleading so perhaps that behaviour could be changed so as to be more consistent.

**Comment by devnulli** [comment]
Great Feedback, thanks. I'll look into it
