### ISSUE TITLE
RD Gateway support

### ISSUE THREAD

**Issue by Paarsch** [devnulli/EvlWatcher#66]
Hi! 

After researching an issue with a RDS envoirment, i came across your application. It looks awesome, simple and to the point. I Do have a question on implememting it though; how does a setup with a RD Gateway work? is EvlWatcher installed on the central RD gateway? or on each RDS host within the farm? 

Kind Regards.

**Comment by devnulli** [comment]
Hi, i can't directly answer your question, but it should be installed on the system where the event log entries for failed logins are being generated.
My guess would be on each host, but you can only know for sure when you try it. Log on with incorrect credentials into a host via RDS and check the Windows Event Log.
