### ISSUE TITLE
Version 2.0 suddenly being flagged as severe "Trojan:MSIL/Masslogger.VN!MTB"

### ISSUE THREAD

**Issue by Adambean** [devnulli/EvlWatcher#67]
Hello,

It appears as of today Microsoft's Windows Defender is flagging the installer for version 2.0 as a severe trojan, specifically "Trojan:MSIL/Masslogger.VN!MTB".

![image](https://user-images.githubusercontent.com/1108717/116899296-4bcb7f00-ac2f-11eb-951a-2b53e371dd22.png)

As this is on a network share of my pooled software downloads I couldn't be sure if it's the installer specifically being pointed out or the actual application binary within.

Obviously I'd be quite sure there isn't a genuine risk here, particularly as both [Jotti's scanner](https://virusscan.jotti.org/en-GB/filescanjob/skx8i1t28x) finds nothing and [VirusTotal](https://www.virustotal.com/gui/file/a1a660f69729e9fbb255979c88eea3556a3477fb25b192fac17e3caf58b1e203/detection) looks like detections are just machine learned, but you'll likely need to submit your binaries to Microsoft for closer inspection and delisting here: https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by devnulli** [comment]
Hi, this is fixed in version 2.1, see #32 
EvlWatcher 2.0 was an unsigned dll, and while its most probably not a virus (you can check by checking the hash), the defender heuristics see that it has a kind of unsafe behaviour for a unsigned dll (like messing with the firewall).

closed as duplicate

**Comment by Adambean** [comment]
Sorry, didn't spot #32. Thanks for resolving this. :)
