### ISSUE TITLE
Remote access sample, please help with task.

### ISSUE THREAD

**Issue by Patrick524** [devnulli/EvlWatcher#70]
Hello, please provide suggested new task details for config file based on the sample below.

Log Name:      System
Source:        RemoteAccess
Date:          11/9/2020 1:47:42 AM
Event ID:      20271
Task Category: None
Level:         Warning
Keywords:      Classic
User:          N/A
Computer:      
Description:
CoId={NA}: The user Administrator connected from 45.146.164.159 but failed an authentication attempt due to the following reason: The remote connection was denied because the user name and password combination you provided is not recognized, or the selected authentication protocol is not permitted on the remote access server.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="RemoteAccess" />
    <EventID Qualifiers="0">20271</EventID>
    <Level>3</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-09T09:47:42.000000000Z" />
    <EventRecordID>649418</EventRecordID>
    <Channel>System</Channel>
    <Computer></Computer>
    <Security />
  </System>
  <EventData>
    <Data>{NA}</Data>
    <Data>Administrator</Data>
    <Data>45.146.164.159</Data>
    <Data>The remote connection was denied because the user name and password combination you provided is not recognized, or the selected authentication protocol is not permitted on the remote access server.</Data>
    <Data>0x10</Data>
    <Binary>B3020000</Binary>
  </EventData>
</Event>

**Comment by devnulli** [comment]
hi, 
could you try to add this to the tasks
[testtask.txt](https://github.com/devnulli/EvlWatcher/files/6680818/testtask.txt)

    
in case it doesnt work, (i dont have such entries), 

could you repost the xml in xml format pls, should look like that?
![image](https://user-images.githubusercontent.com/3720480/122644746-1dd6c700-d117-11eb-8215-5031de80d83e.png)

**Comment by Patrick524** [comment]
Here is the XML image requested.
![remote access error log](https://user-images.githubusercontent.com/86136512/122647956-bcddcd80-d0db-11eb-91fc-c8fc284ba004.JPG)

**Comment by Patrick524** [comment]
A basic regex works in the tester, 
e.g. (\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})
but when adding to the config file, it's seeing something it doesn't like, won't start the service.

**Comment by devnulli** [comment]
hi patrick,

did you try to put the task (see above, testtast.txt) into your config?
if so, did it work?

greetings, Mike

**Comment by Patrick524** [comment]
Yes have tried, sorry but it's still not working.

**Comment by Patrick524** [comment]
![regex failing](https://user-images.githubusercontent.com/86136512/123559300-079cbc80-d750-11eb-98a7-48ddc3d5d8d1.JPG)

**Comment by devnulli** [comment]
hi, 

sorry for the delay (im a fresh father now :heart: ) 

you could try the following regex: 

    Data\>(\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3})\<\/Data

as in [this sample](https://regex101.com/r/sCLBm4/1)

please note, when you copy the regex into the xml, the regex needs to be escaped, so in the xml, it should look like this:

    Data\&gt;(\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3})\&lt;\/Data

if you want to escape regexes for xml, you can also use [this online tool](https://www.freeformatter.com/xml-escape.html)

greetings, 

mike

**Comment by shimuldn** [comment]
@devnulli Congratulations fresh father ❤️ ❤️

**Comment by devnulli** [comment]
> @devnulli Congratulations fresh father ❤️ ❤️

Thx :grin: :grin:

**Comment by Patrick524** [comment]
Congrats on being a father!  
Sorry it took so long to reply.  The regex works now.  I will be adding comments as I'm testing this on a production system.
![ips regex works](https://user-images.githubusercontent.com/86136512/126915769-4eadce2f-aa8b-4e86-8b0b-a2aecd8f6e5c.JPG)

**Comment by devnulli** [comment]
great, thanks. you should also remove "failed" and "attempt" from the boosters for it to work. 
if there are any more questions, just reopen the issue.

**Comment by Patrick524** [comment]
> great, thanks. you should also remove "failed" and "attempt" from the boosters for it to work.
> if there are any more questions, just reopen the issue.

Can you remind me why those terms should be removed from the boosters?  In the example you provided at the start of the issue thread, testtast.txt, those boosters are used?

**Comment by devnulli** [comment]
sure. before the service tries to matches the pattern, it checks if these words are present (that is because regex pattern matching is a very expensive operation).  so, to keep cpu usage low, the service will check if the given booster words are present in the event log entry, before going further. 

if i had those boosters in the original txt file, because in your original posting, this text was present, but looking at your follow up posts, it seems to be missing in the xml. 

if these words are still present in a typical 20271 event, you can of course keep them.
