### ISSUE TITLE
Persistent temp bans after reboot 

### ISSUE THREAD

**Issue by dpinse** [devnulli/EvlWatcher#74]
Restore temp bans after server reboot or log the ban count and apply to future bans.

**Comment by devnulli** [comment]
hi,
 
i also thought about that, but when you look into that, you come to the conclustion that its way too much effort for what it's worth.
temp bans would be restored when the attacker is still present at reboot, and if he is not, its no point in temp banning hime

im sorry, but i wont fix that one in the near future
