### ISSUE TITLE
Support IPv6 addresses

### ISSUE THREAD

**Issue by Pegasus-RPG** [devnulli/EvlWatcher#81]
Hello. Does EvlWatcher already support IPv6 addresses? I don't see the standard link-local addresses in the default white list so I'm assuming not.

So this is a feature request to add IPv6 support. :)

**Comment by devnulli** [comment]
I think I could do that but i would need an example log entry. 

Let's also ask @JReming85 if he maybe happens to have Ipv6 bruters.

**Comment by geoced** [comment]
Here is an example of an OpenSSH event for an IPv6 address. It's a link-local address, so it should be whitelisted, assuming the default list of whitelisted IP patterns is updated to include IPv6 addresses as well.

sshd: Failed password for user from fe80::f829:87f0:45c6:192a%15 port 2420 ssh2
