### ISSUE TITLE
Issue: Cloudflare plan / Blocking Cloudflare source IP. / Reverse Proxy issues

### ISSUE THREAD

**Issue by Shidapu** [devnulli/EvlWatcher#84]
Heya, im having issues with the application blocking Cloudflare source IP: 172.32.0.1 as the random person/bot is trying different usernames to login remotely. When the application blocks this IP, all my websites dies, because the Cloudflare IP is my passage for everything.

I have whitelisted the IP, but i cant see the real IP the attacker is sending from.

**Comment by devnulli** [comment]
As a reverse proxy, all visitors to your site will come through Cloudflare IP addresses, but will include headers identifying the real source:
CF-Connecting-IP
X-Forwarded-For

the question is: are those headers contained in the logs ? could you post the original xml entry?
