### ISSUE TITLE
0.0.0.0

### ISSUE THREAD

**Issue by PavelDmitrenko** [devnulli/EvlWatcher#87]
The ipv4 address 0.0.0.0, which under [some circumstances](https://digirati82.com/2015/10/05/windows-7-2008-rdp8-incorrect-source-network-address/) appears in the Windows logs, is automatically added to the blocked list, thus blocking all subnets.

**Comment by chernots** [comment]
[](url
![photo_2022-02-25_11-23-45](https://user-images.githubusercontent.com/68702990/155690735-309ea79e-36d7-470d-9b5e-7f605d9c57f3.jpg)
)

**Comment by devnulli** [comment]
Thanks. Nice find.

Will fix that.

Workaround: add 0.0.0.0 to the Whitelist, of course
