### ISSUE TITLE
Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by kimboslice99** [devnulli/EvlWatcher#88]
Seeing `Collection was modified; enumeration operation may not execute.` in the live output, what does this mean?

**Comment by devnulli** [comment]
hi, this seems to be a programming error that can happen while multithreading. 
do you see any more output?

**Comment by kimboslice99** [comment]
No other output, I notice this occurs every once in a while (every few weeks maybe?). A restart of the service seems to resolve it, at least until it reoccurs

Is there some place I might find a logfile so I can trace back to the first occurrence?

**Comment by devnulli** [comment]
you could check the windows event log (application) if there are any events with source EvlWatcher, and see if theres more there

**Comment by kimboslice99** [comment]
Haven't seen anything in the event log, will update this thread when/if I do find anything

**Comment by MadCowChicken** [comment]
I'm getting the same thing (`Collection was modified; enumeration operation may not execute.`)

**Comment by devnulli** [comment]
since the eventlog does not show errors, it seems to be a bug on the console side. 
i'll look into it

**Comment by KRiZ-R** [comment]
Hi, I just found this program and installed it to test. I see this same problem in the console and eventlogs. This is from the eventlog:

Log Name:      Application
Source:        EvlWatcher
Date:          6/2/2022 7:51:26 AM
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      TESTRDS2022
Description:
Collection was modified; enumeration operation may not execute.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="EvlWatcher" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-02T05:51:26.1807342Z" />
    <EventRecordID>16549</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>TESTRDS2022</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Collection was modified; enumeration operation may not execute.</Data>
  </EventData>
</Event>

**Comment by devnulli** [comment]
cant reporduce .( im closing this until its being reported again

**Comment by did-vmonroig** [comment]
Same issue in Windows 2019. Restarting service does not help.

**Comment by xihajim** [comment]
Same issue in Windows 2012.

**Comment by devnulli** [comment]
hmmmm..... are you running the current version of evlwatcher? if so, i might have to reopen that.

**Comment by Nionor** [comment]
Ya version 2.1.5

I have around 2300 banned IPs if that could matter.

**Comment by devnulli** [comment]
and did you use the ui or was it just dying without you doing anything?

**Comment by Nionor** [comment]
I can't say for sure but I think I had the UI open.
Exactly every 30 sec I would say.
![image](https://github.com/devnulli/EvlWatcher/assets/36626165/99ee0091-feca-4cbe-aa0e-78f8b1f36718)
