### ISSUE TITLE
event log

### ISSUE THREAD

**Issue by brighthorizon** [devnulli/EvlWatcher#89]
Just wondering if anyone else gets this message in their logs? What does it mean and is there a fix?
Warning: Task BlockRDPBrutersByRdpCore140 takes a lot of resources. This can make your server vulnerable to DOS attacks. Try better boosters.

**Comment by devnulli** [comment]
hi, this warning message indicates that it takes EvlWatcher more than 500 milliseconds to check the configured timeframe for bruters.

this could be that  

a) your timeframe is too big (e.g. you look too far in tha past)
b) someone is ridiculously fast in changing ips and retrying (e.g. you get a LOT of event log entries)
c) your pc is rediculously slow

it's not a problem at all, but evlwatcher gives you that warning, so you can see whats up

**Comment by brighthorizon** [comment]
got it thanks, i'll keep monitoring it

**Comment by MadCowChicken** [comment]
What does "try better boosters" mean?
