### ISSUE TITLE
XXX Task takes a lot of resources [some reports of CPU / Duration of Log analysis exceeds 500 ms]

### ISSUE THREAD

**Issue by smertrius01** [devnulli/EvlWatcher#92]
Hi I am getting this warning nearly constant but im unsure how to resolve.
Its installed on a fresh windows 2019 server and CPU at 1% RAM at 9% total while running.

I dont see any IP v6 being banned nor do i see any issues relating to it in event views so im not sure why im even getting this warning. It may not be an issue with Evlwatcher but without knowing why im getting it I dont know where to even look to see if its a setting issue ect.

Any help much appreciated

**Comment by devnulli** [comment]
Hi.

- Did you change anything in the config file? (especially things that make more events relevant, like increasing the timeframe) ?

**Comment by smertrius01** [comment]
Hi, No changes at all to the software, the test server in question has had dns, iis and smartermail installed but it only set to serve webmail with no traffic being generated (legitimate traffic). After getting the message i have changing log level to debug.

It is a 12 core 3.6Ghz 64GB ram with NVMe drives so i was thinking the message could be a stock message if a setting is enabled as this was test server with nearly all resources still available. I thought it could have been a bug or unintended consequence of something else?

The actual message that is displayed in the console and in the event viewer under application as a warning is as follows:
"Warning: Task BlockRDPBrutersByRdpCore131_IPV6 takes a lot of resources. This can make your server vulnerable to DOS attacks. Try better boosters."
This is from the warning in event viewer in xml (I have removed the left angled bracket):
Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
System>
Provider Name="EvlWatcher" /> 
EventID Qualifiers="0">0</EventID> 
Level>3</Level> 
Task>0</Task> 
Keywords>0x80000000000000</Keywords> 
TimeCreated SystemTime="2022-04-07T06:33:05.421277400Z" /> 
EventRecordID>12671064</EventRecordID> 
Channel>Application</Channel> 
Computer>Titan</Computer> 
Security /> 
/System>
EventData>
Data>Warning: Task BlockRDPBrutersByRdpCore131 takes a lot of resources. This can make your server vulnerable to DOS attacks. Try better boosters.Data> 
 EventData>
Event>

Should the app be posting around 380 events per second to the application log? Console states it works for a few seconds and sleeps for 30s but from the application log that doesnt seem to be the case?

Im also getting this message in the console so im not sure if its related:
7/04/2022 07:33:05 - [Debug]: Booster: 131
07/04/2022 07:33:05 - [Debug]: Booster not in XML, aborting.

**Comment by devnulli** [comment]
hm. normally it shouls work a few hundred ms and then sleep.

since this is the 2nd issue and its the same task, ill look into the regex

**Comment by ixion160** [comment]
Hello,
I have exactly the same message as [smertrius01] in the Windows logs but that said, everything works perfectly except that as for [smertrius01], there is excessive logging in **Windows logs --> Applications.**

**The message generated is the following:**

`Warning: Task BlockRDPBrutersBySecurity4625 takes a lot of resources. This can make your server vulnerable to DOS attacks. Try better boosters.`

I installed EvlWatcher to block SSH login attempts on my Windows 2019 server which works as a sftp server for users with a password account.
Nothing to complain about, you did an excellent "fail2ban like" :-)

But indeed, it takes a lot of CPU resources and it fills the event viewer logs...

For my implementation, I have only opened the SSH protocol on the company firewall.
It seems to me that on my server, it is only the RDP check that takes a lot of resources... 

To modify the .XML config file, if I switch to "Active=False" the following tasks:
```
 <Task Name="BlockRDPBrutersBySecurity4625" Active="true">
<Task Name="BlockRDPBrutersByRdpCore140" Active="true">
<Task Name="BlockRDPBrutersByRdpCore131_IPV6" Active="true">
...
```

I think this will be enough to stop the excessive logging as well as the CPU overload without adversely affecting the operation of my SSH rule below:
`<Task Name="BlockSSHBrutersByOpenSsh" Active="true">`

Correct ?

Thanks again for this nice implementation of "fail2ban" for Windows ;-)

Jean Berthold

**Comment by devnulli** [comment]
i will classify this CPU sink as a bug now

**Comment by devnulli** [comment]
> Hello, I have exactly the same message as [smertrius01] in the Windows logs but that said, everything works perfectly except that as for [smertrius01], there is excessive logging in **Windows logs --> Applications.**
> 
> **The message generated is the following:**
> 
> `Warning: Task BlockRDPBrutersBySecurity4625 takes a lot of resources. This can make your server vulnerable to DOS attacks. Try better boosters.`
> 
> I installed EvlWatcher to block SSH login attempts on my Windows 2019 server which works as a sftp server for users with a password account. Nothing to complain about, you did an excellent "fail2ban like" :-)
> 
> But indeed, it takes a lot of CPU resources and it fills the event viewer logs...
> 
> For my implementation, I have only opened the SSH protocol on the company firewall. It seems to me that on my server, it is only the RDP check that takes a lot of resources...
> 
> To modify the .XML config file, if I switch to "Active=False" the following tasks:
> 
> ```
>  <Task Name="BlockRDPBrutersBySecurity4625" Active="true">
> <Task Name="BlockRDPBrutersByRdpCore140" Active="true">
> <Task Name="BlockRDPBrutersByRdpCore131_IPV6" Active="true">
> ...
> ```
> 
> I think this will be enough to stop the excessive logging as well as the CPU overload without adversely affecting the operation of my SSH rule below: `<Task Name="BlockSSHBrutersByOpenSsh" Active="true">`
> 
> Correct ?
> 
> Thanks again for this nice implementation of "fail2ban" for Windows ;-)
> 
> Jean Berthold

disabling the RPD Tasks will deactivate the CPU usage, yep.

**Comment by devnulli** [comment]
i removed the event log spamming, increased the gap for the warning a bit, and added a better explainatory text

**Comment by devnulli** [comment]
> I've looked through my event logs for anything matching 140, and not seeing anything, but this continues to cycle through my event logs constantly.
> 
> Mine are nearly all 4625, so I'm curious what is triggering this.
> 
> Thanks!

#94 also goes in this direction

**Comment by smertrius01** [comment]
Hi,
sorry for the delay in replying. I have attached 2 sheets with around 10 mins ish of both the application e3vents and the security events in that same time frame ish (for some reason it seems the time might not be in the correct order once it was saved, it looks like its starts at 11:43 but it has 11:41 in there also?? It does seem to have gaps now in the application view which it didn't before it banned IP's.

I just want to make clear this is not impacting the server by loading up the CPU, it hovers at 1% total usage so definitely
[10 mins app view.xlsx](https://github.com/devnulli/EvlWatcher/files/8488736/10.mins.app.view.xlsx)
[10 mins security view.xlsx](https://github.com/devnulli/EvlWatcher/files/8488737/10.mins.security.view.xlsx)
 not impacting load in that sense. It was due to having no load but still getting the error message I thought it may have been a stock message when used or it was a bug reporting high CPU when that wasn't the case. 

I must say it is very handy bit of software and I thank you for all your hard work :)

[10 mins app view.xlsx](https://github.com/devnulli/EvlWatcher/files/8488740/10.mins.app.view.xlsx)
[10 mins security view.xlsx](https://github.com/devnulli/EvlWatcher/files/8488741/10.mins.security.view.xlsx)

**Comment by ixion160** [comment]
Hello, 

also sorry for the delay in my response...


I have  ID 4625 entries in the security logs but not so much... and only about sshd.exe, with this kind of message:

**An account failed to log on.

Subject:
	Security ID:		SYSTEM
	Account Name:		SRV-xxxx$
	Account Domain:		xxxxx
	Logon ID:		0x3E7

Logon Type:			8

Account For Which Logon Failed:
	Security ID:		NULL SID
	Account Name:		NOUSER
	Account Domain:		xxxx

Failure Information:
	Failure Reason:		Unknown user name or bad password.
	Status:			0xC000006D
	Sub Status:		0xC0000064
**

In the same time, the application log continue to log the message:

`Warning: Task BlockRDPBrutersBySecurity4625 takes a lot of resources. This can make your server vulnerable to DOS attacks. Try better boosters.`

So, I'll deactivate the tasks "BlockRDP..." to stop this message flow...

thanks for your help

Jean

**Comment by devnulli** [comment]
so, i think this warning hast gone crazy and does warn about CPU spikes that are not there.
i will release a new version next week and fix this, as it is stuffing the event log

**Comment by devnulli** [comment]
@smertrius01  please check out the new release 2.1.5 instead of deactivating the task

**Comment by smertrius01** [comment]
Hi, Ive been back on the test server today updated EvlWatcher and can confirm the event viewer>applications is now very clean and only a few posts a min depending on when IP's are being banned. I do wish i had looked at the other reported issues namely the ban list being lost on update or i had just backed up in case lol 
I quickly renamed the ban list in firewall so i can move them back into Evlwatcher as and when i have the time. 

Thank you very much for all the effort you have put in in making and resolving any issues.
