### ISSUE TITLE
Warning: Task BlockRDPBrutersByRdpCore140 takes a lot of resources. This can make your server vulnerable to DOS attacks. Try better boosters.

### ISSUE THREAD

**Issue by TechnoJaguar** [devnulli/EvlWatcher#94]
I've looked through my event logs for anything matching 140, and not seeing anything, but this continues to cycle through my event logs constantly.

Mine are nearly all 4625, so I'm curious what is triggering this.

Thanks!

**Comment by devnulli** [comment]
there seems to be an issue with evlwatcher taking longer than 500 milliseconds to analyze the logs. i think this is the same problem than #92, so i'll put this XXX takes a lot of resources problem together there
