### ISSUE TITLE
whitelist

### ISSUE THREAD

**Issue by chernots** [devnulli/EvlWatcher#96]
Hi, 
why is the whitelist being overwritten by banlist?
![bug](https://user-images.githubusercontent.com/68702990/164419600-1c3a69b1-9e1f-4c65-967f-cec621a0b731.png)
 
 That actually same IPs...

**Comment by devnulli** [comment]
Hi, is this issue still present in the latest Version
Which version are you using?
(Possible duplicate of #64 )
