### ISSUE TITLE
Ability to communicate with gateway firewall or maintain a txt list of blocked IP addesses

### ISSUE THREAD

**Issue by phil-highrez** [devnulli/EvlWatcher#99]
It would be *really* neat if it could interface with an external API to add/remove firewall rules (for example OPNSense/pfSense using their API's to add rules to the gateway firewall as well as/rather than the local Windows firewall).

Alternatively, just create/maintain a simple text file list of blocked IP's that can be automatically sucked in to the OPNSense firewall aliases list every so often, so the gateway itself can block the external IP's site-wide. 

This may apply to other gateway firewalls, I personally am only familiar with how it works with OPNSense and pfSense (very similar). and I understand most consumer routers wont easily support this.

Again, may be able to help on this one!

**Comment by devnulli** [comment]
hi, you can just parse config.xml, the list is persisted there
